# Generated by Django 2.2.17 on 2021-01-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210109_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='車種')),
                ('size', models.CharField(max_length=100, verbose_name='サイズ')),
            ],
        ),
    ]
