# Generated by Django 2.2.17 on 2021-01-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
