# Generated by Django 2.2.17 on 2021-01-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='staff',
        ),
    ]
