# Generated by Django 2.2.17 on 2021-02-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210129_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='メールアドレス'),
        ),
    ]
